# Generated by Django 4.2.7 on 2025-06-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='party',
            field=models.CharField(blank=True, default='Independent', help_text='Political party or affiliation', max_length=100),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='slogan',
            field=models.CharField(blank=True, help_text='Campaign slogan or motto', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='manifesto',
            field=models.TextField(blank=True, help_text='Your campaign manifesto and promises'),
        ),
    ]
