# Generated by Django 4.2.7 on 2025-06-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_candidateprofile_party_candidateprofile_slogan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='party',
        ),
    ]
