# Generated by Django 4.2.7 on 2025-06-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterprofile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='voterprofile',
            name='year_of_study',
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics and Communication'), ('ME', 'Mechanical'), ('CE', 'Civil'), ('EE', 'Electrical')], default='CSE', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year_of_study',
            field=models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], default='1', max_length=1),
        ),
    ]
